services:
  backend:
    container_name: "promis_backend"
    build: backend/
    restart: unless-stopped
    ports:
      - "8000:8000"
    expose:
      - "8000"

  frontend:
    container_name: "promis_frontend"
    build: frontend/
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"