name: Deploy Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[doc]"
          pip install git+https://github.com/simon-kohaut/problog.git@dcproblog_develop
          sudo apt-get install pandoc -y

      - name: Build documentation
        run: |
          mkdir -p doc/source/notebooks
          cp examples/*.ipynb doc/source/notebooks
          sphinx-build -b html doc/source _build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/html
